### ISSUE TITLE
[1.18] Client crash when a creeper follows player into portal

### ISSUE THREAD

**Issue by kwpugh** [kyrptonaught/customportalapi#41]
log:  https://pastebin.com/UTs2uTwB

Seems as though a creeper chased a player into a portal and crashed the client when the creeper made contact with it.

using api:  0.0.1-beta46v2-1.18

**Comment by ClaudiusMinimus** [comment]
It can also happen if a player or even a bat goes through the portal

[99-fabric-crash-reports_crash-2021-12-05_19.38.59-server.txt](https://github.com/kyrptonaught/customportalapi/files/7656834/99-fabric-crash-reports_crash-2021-12-05_19.38.59-server.txt)

**Comment by kwpugh** [comment]
Players are not the problem, just mob entities going through the portals

**Comment by kyrptonaught** [comment]
Interesting, both cases are with the portal at the newly added below 0 part of the world. Which the player can go through just fine, but entities cannot. This is not the case above y=0. Investigating

**Comment by kyrptonaught** [comment]
It was caused by a check for y>0 in the code. Interesting that this didn't effect players. I suspect lots of mods will have problems with this new <0 world gen.

Beta 47 fixes this

**Comment by kwpugh** [comment]
I made a portal at y = -52 and pushed some bats and a sheep through it, no crashes.  Thanks.

**Comment by lexi-the-cute** [comment]
yep. i had a creeper go into a portal at the same time it exploded and it crashed my server with 

```
[08:16:00] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Colliding entity with block
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zlh000$carpet$modifiedRunLoop(MinecraftServer.java:12942) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
        at net.kyrptonaught.customportalapi.portal.linking.PortalLinkingStorage.getDestination(PortalLinkingStorage.java:50) ~[customportalapi-0.0.1-beta64-1.20-1536c58c09495c99.jar:?]
        at net.kyrptonaught.customportalapi.util.CustomTeleporter.customTPTarget(CustomTeleporter.java:65) ~[customportalapi-0.0.1-beta64-1.20-1536c58c09495c99.jar:?]
        at net.kyrptonaught.customportalapi.util.CustomTeleporter.TPToDim(CustomTeleporter.java:46) ~[customportalapi-0.0.1-beta64-1.20-1536c58c09495c99.jar:?]
        at net.kyrptonaught.customportalapi.CustomPortalBlock.method_9548(CustomPortalBlock.java:110) ~[customportalapi-0.0.1-beta64-1.20-1536c58c09495c99.jar:?]
        at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:1121) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.redirect$cce000$carpet-fixes$checkBlockCollisionBetter(class_1297.java:9384) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5852(class_1297.java:1137) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.redirect$cce000$carpet-fixes$onEntityCollision(class_1297.java:9352) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5784(class_1297.java:799) ~[server-intermediary.jar:?]
        at net.minecraft.class_1542.method_5773(class_1542.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[server-intermediary.jar:?]
        at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[server-intermediary.jar:?]
```
